# Generated by Django 5.2.7 on 2025-11-08 06:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foods', '0001_initial'),
        ('restaurants', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='food',
            name='food_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='food',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='restaurant', to='restaurants.restaurant'),
        ),
    ]
