# Generated by Django 5.2.7 on 2025-11-07 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Restaurant',
            fields=[
                ('restaurant_id', models.AutoField(primary_key=True, serialize=False)),
                ('res_name', models.CharField(max_length=100)),
                ('res_address', models.TextField()),
                ('res_phone', models.CharField(blank=True, max_length=15, null=True)),
                ('res_lat', models.FloatField(blank=True, null=True)),
                ('res_long', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
